import type { Metadata } from "next";

import {
  Sidebar,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebarContent } from "./sidebar/sidebar";

export const metadata: Metadata = {
  title: "Kenakata App",
  description: "Generated by create kenakata app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <div className="flex h-screen">
            <Sidebar className="w-64">
              <AppSidebarContent />
            </Sidebar>
            <main className="flex-1 p-4">
              <SidebarTrigger />
              {children}
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
