import type { Metadata } from "next";
import {
  Sidebar,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebarContent } from "./sidebar/sidebar";

import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/navbar/navbar";
import Footer from "./footer/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kenakata App",
  description: "Generated by create kenakata app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div className="flex h-screen">
            <Sidebar className="w-64">
              <AppSidebarContent />
            </Sidebar>
            <main className="flex-1 p-4">
              <SidebarTrigger />
              <Navbar />
              {/* Page Content */}
              <div className="mt-4">{children}</div>
              <Footer></Footer>
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
